name: Native Image Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  native-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Install musl
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build Native Image
        run: mvn -B -Pnative package -Dnative-image.buildArgs="--static --libc=musl"
        
      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: check_mbean-linux-amd64
          path: target/check_mbean
